# ------------------------------------------------------------------------------
# File: train_dcgan.py
# This implementation is partially based on the official TensorFlow DCGAN tutorial:
# https://www.tensorflow.org/tutorials/generative/dcgan
# ------------------------------------------------------------------------------


import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import os

# Global variables
generator = None
discriminator = None
g_optimizer = None
d_optimizer = None
batchz_size = None
dim = None


"""
Objective of discriminator and generator(same as the objective function of original GAN):
discriminator: maximize E(log(D(x))) + E(log(1 - D(G(z))))  ->  minimize -E(log(D(x))) - E(log(1 - D(G(z))))
generator: maximize log(D(G(z)))  ->  minimize -E(log(D(G(z)))) 
"""

def loss_discriminator(real, fake):
    cross_entropy = tf.keras.losses.BinaryCrossentropy(from_logits=True)
    real_loss = cross_entropy(tf.ones_like(real), real)
    fake_loss = cross_entropy(tf.zeros_like(fake), fake)
    return real_loss + fake_loss

def loss_generator(fake):
    cross_entropy = tf.keras.losses.BinaryCrossentropy(from_logits=True)
    return cross_entropy(tf.ones_like(fake), fake)

"""
Perform one training step of DCGAN for both the generator and discriminator.
1. Samples random noise z.
2. Produces fake images using the generator.
3. Trains discriminator using both real and fake images.
4. Computes the losses of discriminator and generator.
5. Updates the discriminator parameters.
6. Updates the generator parameters.
7. Return losses of generator and discriminator

"""

def train_step(real_images):
    # 1. Sample random noise
    z = tf.random.uniform([batchz_size, dim], minval=-1., maxval=1.)

    with tf.GradientTape() as d_tape, tf.GradientTape() as g_tape:

        # 2. Generate fake images
        fake_images = generator(z, training=True)

        # 3. Train discriminator
        real = discriminator(real_images, training=True)
        fake = discriminator(fake_images, training=True)

        # 4. Compute losses
        d_loss = loss_discriminator(real, fake)
        g_loss = loss_generator(fake)

    # 5. Update parameters of discriminator
    d_grads = d_tape.gradient(d_loss, discriminator.trainable_variables)
    d_optimizer.apply_gradients(zip(d_grads, discriminator.trainable_variables))

    # 6. Update parameters of generator
    g_grads = g_tape.gradient(g_loss, generator.trainable_variables)
    g_optimizer.apply_gradients(zip(g_grads, generator.trainable_variables))

    # 7. Return losses of generator and discriminator
    return d_loss, g_loss


"""
Train the DCGAN model for a given number of epochs.

This function iterates through the dataset, performs one training step on both
the generator and discriminator for each batch, records the losses, saves 
generated sample images, and stores model weights.
"""

def train(dataset, epochs):
    for epoch in range(epochs):
        print(f"Epoch {epoch+1}/{epochs}")
        d_losses = []
        g_losses = []

        for real_images in dataset:
            d_loss, g_loss = train_step(real_images)
            d_losses.append(d_loss)
            g_losses.append(g_loss)

        # Print loss
        print(f"  d_loss: {np.mean(d_losses):.4f}, g_loss: {np.mean(g_losses):.4f}")

        # Save image grid for this epoch
        generate_and_save_images(generator, epoch+1)

        # Save model
        generator.save_weights("generator_celebA.h5")
        discriminator.save_weights("discriminator_celebA.h5")


"""
Generate and save sample images from the generator at a given training epoch.

This function:
1. Samples random noise vectors z.
2. Uses the generator to produce 16 fake images.
3. Applies inverse normalization to convert images from [-1, 1] back to [0, 255].
4. Generates the images into a 4×4 grid and saves them.
"""

def generate_and_save_images(generator, epoch, z_dim=100):
    # Generate 16 images
    z = tf.random.uniform([16, z_dim], minval=-1., maxval=1.)
    predictions = generator(z, training=False)

    # Reverse normalization
    imgs = ((predictions + 1.0) * 127.5).numpy().astype("uint8")

    fig = plt.figure(figsize=(6,6))
    for i in range(16):
        plt.subplot(4,4,i+1)
        plt.imshow(imgs[i])
        plt.axis('off')

    os.makedirs("generated_faces", exist_ok=True)
    plt.savefig(f"generated_faces/epoch_{epoch:03d}.png")
    plt.close()
    
    
    

    
    



'''
Date: <09/11/2025>
Written by: <Ziyi Zhao> <zz3459@columbia.edu>

The code in this file was fully implemented by the student.
It has not been generated by AI tools, and it has not been copied 
from any external resource.
'''


# 
# ADDED FOR TASK 3 (To avoid conflict)
# ==================================================================



def generate_and_save_images_task3(generator, epoch, save_dir, z_dim=100):
    """
    Custom generation function for Task 3.
    Allows specifying a save directory to avoid mixing with 'generated_faces'.
    """
    # Generate 16 images
    z = tf.random.uniform([16, z_dim], minval=-1., maxval=1.)
    predictions = generator(z, training=False)

    # Reverse normalization: [-1, 1] -> [0, 255]
    imgs = ((predictions + 1.0) * 127.5).numpy().astype("uint8")

    fig = plt.figure(figsize=(6,6))
    for i in range(16):
        plt.subplot(4,4,i+1)
        plt.imshow(imgs[i])
        plt.axis('off')

    # Create directory if not exists
    os.makedirs(save_dir, exist_ok=True)
    
    # Save image
    plt.savefig(f"{save_dir}/epoch_{epoch:03d}.png")
    plt.close()

def train_task3(dataset, epochs, model_name="task3_imagenet", image_dir="task3_images"):
    """
    Custom training loop for Task 3.
    - Saves images to 'image_dir'
    - Saves models to 'generator_{model_name}.h5'
    """
    print(f"Starting Task 3 Training -> Models: {model_name}, Images: {image_dir}")
    
    for epoch in range(epochs):
        print(f"Epoch {epoch+1}/{epochs}")
        d_losses = []
        g_losses = []

        for real_images in dataset:
            # We reuse the global 'train_step' because the logic is the same
            d_loss, g_loss = train_step(real_images)
            d_losses.append(d_loss)
            g_losses.append(g_loss)

        # Print loss
        print(f"  d_loss: {np.mean(d_losses):.4f}, g_loss: {np.mean(g_losses):.4f}")

        # Save images
        generate_and_save_images_task3(generator, epoch+1, image_dir, dim)

        # 2 Save models
   
        generator.save_weights(f"generator_{model_name}.h5")
        discriminator.save_weights(f"discriminator_{model_name}.h5")
        
    print(f"Training Complete. Model saved as discriminator_{model_name}.h5")
